[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --before usb-reset --after watchdog-reset"
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]
build-std = ["alloc", "core"]

[env]
DEFMT_LOG = "info"
