//! Authentication and session management types.
//!
//! # Pairing flow (BLE-bootstrapped PSK):
//!
//! 1. Cube generates a 256-bit random PSK on first boot and stores it in NVS.
//! 2. When the app connects to the BLE Pairing service and writes to
//!    `PAIRING_CHALLENGE_CHAR`, the cube returns a 6-digit numeric code via
//!    the `PAIRING_INFO_CHAR` (Read). In production this would show on an LED
//!    face; for MVP it's just readable over BLE + printed via defmt.
//! 3. The user enters the 6-digit code in the app.  The app sends a
//!    `PairingConfirm` message to `PAIRING_CONFIRM_CHAR` containing:
//!    - The 6-digit code (proves user has physical proximity).
//!    - A random 32-byte app-session-public nonce.
//! 4. If the code matches, the cube:
//!    - Returns the pre-shared key (PSK) XOR'd with SHA-256(app_nonce ++ code).
//!      This ensures only the app that saw the code can derive the PSK.
//!    - Saves the app's identity (a hash of their nonce) in its list of paired
//!      apps.
//! 5. For subsequent connections, the app proves knowledge of the PSK by
//!    computing `HMAC-SHA256(PSK, challenge)` where `challenge` is a random
//!    value the cube writes to `PAIRING_CHALLENGE_CHAR` on each connection.
//!
//! # WiFi HTTP session token:
//!
//! Once the app knows the cube's PSK, it can authenticate HTTP requests:
//! - On each HTTP request, include header `X-Cube-Auth: <hex(HMAC-SHA256(PSK, nonce))>`
//!   where `nonce` is from `GET /auth/challenge`.
//! - The cube validates the HMAC and grants a short-lived session token.

use heapless::String;
use serde::{Deserialize, Serialize};

/// A 6-digit numeric pairing code (decimal string, zero-padded).
pub type PairingCode = String<6>;

/// Sent by the app to initiate pairing — kicks off the challenge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairingChallenge {
    /// Random 32-byte nonce generated by the app.
    pub app_nonce: [u8; 32],
}

/// Sent by the app to confirm pairing after reading the 6-digit code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairingConfirm {
    /// The 6-digit code the user read from the cube.
    pub code: PairingCode,
    /// Same nonce as in PairingChallenge, for binding.
    pub app_nonce: [u8; 32],
}

/// Returned by the cube after successful pairing confirmation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairingResult {
    /// PSK XOR'd with SHA-256(app_nonce ++ code) — the app must undo the XOR
    /// to recover the raw PSK.
    pub masked_psk: [u8; 32],
    /// The cube's device ID (first 6 bytes of MAC, hex-encoded).
    pub device_id: String<12>,
    /// The cube's user-assigned name.
    pub cube_name: String<64>,
}

/// Challenge issued by the cube on every new BLE connection (after initial
/// pairing is complete).  The app responds with an HMAC to prove PSK
/// knowledge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionChallenge {
    /// 16-byte random challenge.
    pub challenge: [u8; 16],
}

/// App's response to the session challenge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionResponse {
    /// HMAC-SHA256(PSK, challenge) — 32 bytes.
    pub hmac: [u8; 32],
}

/// HTTP authentication challenge (returned by `GET /auth/challenge`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HttpChallenge {
    /// Random 16-byte nonce; the app must HMAC this with the PSK.
    pub nonce: [u8; 16],
    /// Expires in this many seconds.
    pub expires_in: u16,
}

/// HTTP auth header value format: the 32-byte HMAC as hex.
pub const HTTP_AUTH_HEADER: &str = "X-Cube-Auth";
