name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/rust_ci.yml'
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.cargo/config.toml'
      - 'rust-toolchain.toml'
      - '.clippy.toml'
      - 'build.rs'
  pull_request:
    paths:
      - '.github/workflows/rust_ci.yml'
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.cargo/config.toml'
      - 'rust-toolchain.toml'
      - '.clippy.toml'
      - 'build.rs'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - uses: actions/checkout@v4

      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false

      - uses: Swatinem/rust-cache@v2

      - name: Run ${{ matrix.action.command }}
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
